############################
## CHANGE THESE
############################

baseURL: "https://JasonWStewart.github.io/ruffthe.dog"
title: ruffthe.dog

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
