############################
## CHANGE THESE
############################

baseURL: "https://ruffthe.dog"
title: Ruff the Dog

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
