############################
## Navbar
############################

main:
- name: Home
  url: /
  weight: 10
- name: Classes
  url: /classes/
  weight: 20
- name: Blog
  url: /blog/
  weight: 30
- name: About
  url: /about/
  weight: 40