############################
## Author
############################

author:
  name: Ruff
  image: ruff_face.png
  greeting: "I'm a nice puppy!"
  icon: ":dog:"

############################
## Links
############################

links:
  - bluesky: https://bsky.app/profile/ruffthe.dog
  - telegram: https://t.me/Ruffninja82
  - facebook: https://www.facebook.com/ruff.pup.2024
  - email: "mailto:woof@ruffthe.dog?subject=website%20inquiry"
  # - website:
  # - x-twitter:
  # - mastodon:
  # - linkedin:
  # - instagram:
  # - reddit:
  # - telegram:
  # - whatsapp:
  # - signal:
  # - codepen:
  # - dev:
  # - email:
  # - discord:
  # - orcid:
  # - slack:
  # - stack-overflow:
  # - twitch:
  # - patreon:
  # - soundcloud:
  # - dribbble:
  # - stack-exchange:
  # - tiktok:
  # - youtube:
  # - keybase:
  # - flickr:
  # - tumblr:
  # - kickstarter:
  # - snapchat:
  # - bluesky:
  # - bitbucket:
  # - bandcamp:
  # - etsy:
  # - spotify:
  # - pinterest:
  # - strava:
  # - untappd:
  # - skype:
  # - medium:
  # - foursquare:
  # - apple:
  # - amazon:
  # - google:
  # - paypal:
  # - windows:

###############################
## OpenGraph & Twitter Cards
###############################

title: ruffthe.dog
description: ""
images:
  - ruff_face.png
